version: '3.8'

services:
  surveybot-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onow-surveybot-api
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=false
    env_file:
      - .env
    volumes:
      - ./CleanedData:/app/CleanedData
      - ./RawData:/app/RawData
      - ./Graph:/app/Graph
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - surveybot-network

networks:
  surveybot-network:
    driver: bridge 